interface countryType {
  name: string;
}
export const countries: countryType[] = [
  { name: "Argentina" },
  { name: "Australia" },
  { name: "Austria" },
  { name: "Bahamas" },
  { name: "Bahrain" },
  { name: "Bangladesh" },
  { name: "Belgium" },
  { name: "Bolivia" },
  { name: "Brazil" },
  { name: "Bulgaria" },
  { name: "Canada" },
  { name: "Chile" },
  { name: "Colombia" },
  { name: "Costa Rica" },
  { name: "Croatia" },
  { name: "Cyprus" },
  { name: "Czech Republic" },
  { name: "Denmark" },
  { name: "Dominican Republic" },
  { name: "Ecuador" },
  { name: "Egypt" },
  { name: "Estonia" },
  { name: "Finland" },
  { name: "France" },
  { name: "Germany" },
  { name: "Greece" },
  { name: "Guatemala" },
  { name: "Honduras" },
  { name: "Hong-Kong" },
  { name: "Hungary" },
  { name: "Iceland" },
  { name: "India" },
  { name: "Indonesia" },
  { name: "Ireland" },
  { name: "Israel" },
  { name: "Italy" },
  { name: "Jamaica" },
  { name: "Japan" },
  { name: "Jordan" },
  { name: "Kenya" },
  { name: "Kuwait" },
  { name: "Latvia" },
  { name: "Lebanon" },
  { name: "Lithuania" },
  { name: "Luxembourg" },
  { name: "Malaysia" },
  { name: "Maldives" },
  { name: "Malta" },
  { name: "Mauritius" },
  { name: "Mexico" },
  { name: "Morocco" },
  { name: "Netherlands" },
  { name: "New Zealand" },
  { name: "Nicaragua" },
  { name: "Nigeria" },
  { name: "Norway" },
  { name: "Oman" },
  { name: "Pakistan" },
  { name: "Panama" },
  { name: "Paraguay" },
  { name: "Peru" },
  { name: "Philippines" },
  { name: "Poland" },
  { name: "Portugal" },
  { name: "Qatar" },
  { name: "Romania" },
  { name: "Salvador" },
  { name: "Saudi Arabia" },
  { name: "Serbia" },
  { name: "Singapore" },
  { name: "Slovakia" },
  { name: "Slovenia" },
  { name: "South Africa" },
  { name: "South Korea" },
  { name: "Spain" },
  { name: "Sri Lanka" },
  { name: "Sweden" },
  { name: "Switzerland" },
  { name: "Taiwan" },
  { name: "Thailand" },
  { name: "Trinidad and Tobago" },
  { name: "Turkey" },
  { name: "Ukraine" },
  { name: "United Arab Emirates" },
  { name: "United Kingdom" },
  { name: "United States" },
  { name: "Uruguay" },
  { name: "Venezuela" },
  { name: "Vietnam" },
];
